a=int(input("enter your first number"))
b=int(input("enter your second number"))
addition=a+b
subtraction=a-b
multiplication=a*b
division=a/b
print("addition= " , addition)
print("subtraction= ",subtraction)
print("multiplication= ",multiplication)
print("division= " , division)